# Generated by Django 5.0.4 on 2024-04-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(default='producent', max_length=50),
        ),
    ]
