# Generated by Django 5.0.4 on 2024-06-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=200)),
                ('buyer', models.CharField(max_length=200)),
                ('status', models.CharField(default='W toku', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Brak opisu.'),
        ),
        migrations.CreateModel(
            name='NegotiationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.negotiation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
