# Generated by Django 5.0.4 on 2024-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_negotiation_product_description_negotiationproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Brak opisu.', max_length=1500),
        ),
    ]
