# Generated by Django 5.0.4 on 2024-06-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiationproduct',
            name='negotiation',
        ),
        migrations.RemoveField(
            model_name='negotiationproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Negotiation',
        ),
        migrations.DeleteModel(
            name='NegotiationProduct',
        ),
    ]
