# Generated by Django 5.0.4 on 2024-06-15 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_transaction_finalprice_transaction_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 16, 1, 52, 15, 613979)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.CharField(max_length=200),
        ),
    ]
