# Generated by Django 5.0.4 on 2024-05-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_user_2_room_buyer_rename_user_1_room_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='product',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
