# Generated by Django 5.0.4 on 2024-05-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default='W toku', max_length=200),
        ),
    ]
