# Generated by Django 5.0.4 on 2024-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_new_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='new_offer',
            new_name='new_offer_customer',
        ),
        migrations.AddField(
            model_name='room',
            name='new_offer_producent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
